variable "ami" {}
variable "instance_type" {}
variable "vpc_security_group_ids" {}
variable "Name" {}
variable "zone_id" {}
variable "env" {}
variable "domain" {}
variable "from_port_no" {}
variable "to_port_no" {}